# Generated by Django 3.0.4 on 2020-03-05 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200304_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.Topic'),
            preserve_default=False,
        ),
    ]
