# Generated by Django 3.0.4 on 2020-03-11 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_auto_20200305_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='helper',
            field=models.ManyToManyField(related_name='helper', to=settings.AUTH_USER_MODEL),
        ),
    ]
