# Generated by Django 3.0.4 on 2020-03-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20200311_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.SlugField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
